---
- name: Include variables
  include_vars: dir=vars

- name: Create monitoring namespace
  ansible.builtin.command: "kubectl create namespace monitoring"
  ignore_errors: true
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"

- name: Add the Prometheus-Grafana Helm repository
  ansible.builtin.command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  changed_when: false

- name: Update Helm repositories
  ansible.builtin.command: helm repo update
  changed_when: false

- name: Install Prometheus-Grafan-stack using Helm
  ansible.builtin.command: >
    helm upgrade --install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring
  register: helm_result
  changed_when: "'STATUS: deployed' in helm_result.stdout"
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"

- name: Apply Bookinfo sample
  ansible.builtin.shell: "{{ kubectl_bin }} apply -f https://raw.githubusercontent.com/gzeel/k8s-config/refs/heads/main/ingress-grafana-prometheus.yaml"
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"
