---
- name: Include variables
  include_vars: dir=vars

- name: Add the ingress-nginx Helm repository
  ansible.builtin.command: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
  changed_when: false

- name: Update Helm repositories
  ansible.builtin.command: helm repo update
  changed_when: false

- name: Install ingress-nginx using Helm
  ansible.builtin.command: >
    helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx
    --namespace ingress-nginx --create-namespace
  register: helm_result
  changed_when: "'STATUS: deployed' in helm_result.stdout"
  environment:
    KUBECONFIG: "/etc/kubernetes/admin.conf"
