---
- name: Include variables
  include_vars: dir=vars

- name: Get Ansible host IP address
  set_fact:
    ansible_host_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- name: Initialize the Kubernetes Cluster
  command: kubeadm init --pod-network-cidr="{{ pod_network }}" --apiserver-advertise-address="{{ ansible_host_ip }}" --cri-socket=unix:///run/containerd/containerd.sock
  register: kubeadm_init
  failed_when: kubeadm_init.rc != 0

- name: set kube config for user
  block:
    - name: Check if ~/.kube directory exists
      ansible.builtin.stat:
        path: "/home/{{ ansible_user }}/.kube"
      register: kube_directory

    - name: Create ~/.kube directory if it does not exist
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
      when: not kube_directory.stat.exists

    - name: Copy /etc/kubernetes/admin.conf to ~/.kube/config
      ansible.builtin.copy:
        remote_src: true
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ ansible_user }}/.kube/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
  when: kubeadm_init.rc == 0
